using System.Collections;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
#if UNITY_EDITOR
using UnityEditor;
#endif

namespace TieuTienKy.Gameplay.Tests
{
    /// <summary>
    /// Proves the authored CultivatorProxy prefab (rig + AnimationClips +
    /// AnimatorController, generated by VerticalSliceContentBuilder) is a
    /// real, playable Animator/socket pipeline - not just an asset that
    /// imports cleanly. EditMode cannot advance Animator state machine time,
    /// so this must run in Play Mode.
    /// </summary>
    public class CultivatorProxyIntegrationTests
    {
        const string PrefabPath = "Assets/_Project/Prefabs/Characters/CultivatorProxy.prefab";

        GameObject instance;

        [TearDown]
        public void TearDown()
        {
            if (instance != null)
            {
                Object.Destroy(instance);
            }
        }

        GameObject LoadAndInstantiate()
        {
#if UNITY_EDITOR
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(PrefabPath);
            Assert.IsNotNull(prefab, "CultivatorProxy prefab not found at " + PrefabPath);
            instance = Object.Instantiate(prefab);
            return instance;
#else
            Assert.Ignore("Prefab load by asset path requires the Editor; this test only runs in-Editor Play Mode.");
            return null;
#endif
        }

        [UnityTest]
        public IEnumerator Prefab_IsFullyConfigured_WithLiveAnimatorAndSockets()
        {
            GameObject go = LoadAndInstantiate();
            yield return null;

            var presentation = go.GetComponent<CharacterPresentation>();
            Assert.IsNotNull(presentation);
            Assert.IsTrue(presentation.IsConfigured);
            Assert.IsNotNull(presentation.WeaponSocket);
            Assert.IsNotNull(presentation.BodyVfxSocket);
            Assert.IsNotNull(presentation.FeetVfxSocket);
            Assert.IsNotNull(presentation.CastVfxSocket);

            var animator = go.GetComponent<Animator>();
            Assert.IsNotNull(animator.runtimeAnimatorController);
        }

        [UnityTest]
        public IEnumerator PlayBasicAttack_EntersBasicAttackState_ThenReturnsToIdle()
        {
            GameObject go = LoadAndInstantiate();
            yield return null;

            var presentation = go.GetComponent<CharacterPresentation>();
            var animator = go.GetComponent<Animator>();

            presentation.PlayBasicAttack();

            float enterTimeout = Time.realtimeSinceStartup + 2f;
            while (!animator.GetCurrentAnimatorStateInfo(0).IsName("BasicAttack") && Time.realtimeSinceStartup < enterTimeout)
            {
                yield return null;
            }
            Assert.IsTrue(animator.GetCurrentAnimatorStateInfo(0).IsName("BasicAttack"), "Expected to enter BasicAttack state after the trigger.");

            float exitTimeout = Time.realtimeSinceStartup + 3f;
            while (animator.GetCurrentAnimatorStateInfo(0).IsName("BasicAttack") && Time.realtimeSinceStartup < exitTimeout)
            {
                yield return null;
            }

            Assert.IsTrue(animator.GetCurrentAnimatorStateInfo(0).IsName("Idle"), "Expected to return to Idle after the one-shot attack clip finished.");
        }

        [UnityTest]
        public IEnumerator SetMovement_TransitionsFromIdleToRun_AndBack()
        {
            GameObject go = LoadAndInstantiate();
            yield return null;

            var presentation = go.GetComponent<CharacterPresentation>();
            var animator = go.GetComponent<Animator>();

            presentation.SetMovement(1f);
            float timeout = Time.realtimeSinceStartup + 2f;
            while (!animator.GetCurrentAnimatorStateInfo(0).IsName("Run") && Time.realtimeSinceStartup < timeout)
            {
                yield return null;
            }
            Assert.IsTrue(animator.GetCurrentAnimatorStateInfo(0).IsName("Run"));

            presentation.SetMovement(0f);
            timeout = Time.realtimeSinceStartup + 2f;
            while (!animator.GetCurrentAnimatorStateInfo(0).IsName("Idle") && Time.realtimeSinceStartup < timeout)
            {
                yield return null;
            }
            Assert.IsTrue(animator.GetCurrentAnimatorStateInfo(0).IsName("Idle"));
        }

        [UnityTest]
        public IEnumerator PlayDeath_EntersDeathState_AndStays()
        {
            GameObject go = LoadAndInstantiate();
            yield return null;

            var presentation = go.GetComponent<CharacterPresentation>();
            var animator = go.GetComponent<Animator>();

            presentation.PlayDeath();

            float enterTimeout = Time.realtimeSinceStartup + 2f;
            while (!animator.GetCurrentAnimatorStateInfo(0).IsName("Death") && Time.realtimeSinceStartup < enterTimeout)
            {
                yield return null;
            }
            Assert.IsTrue(animator.GetCurrentAnimatorStateInfo(0).IsName("Death"));

            for (int i = 0; i < 10; i++)
            {
                yield return null;
            }

            Assert.IsTrue(animator.GetCurrentAnimatorStateInfo(0).IsName("Death"), "Death should have no exit transition - it must not silently return to Idle.");
        }
    }
}
